### ISSUE TITLE
Pruning directories

### ISSUE THREAD

**Issue by nomeata** [dspinellis/fileprune#1]
(JFTR, this ways already reported by mail).

It would be nice if fileprune was able to prune whole directories. This would probably not go well with with the size constraint (`-s`), but otherwise it should work.

**Comment by nomeata** [comment]
Why did you reopen this; you merged my commit that fixes this? Or did you not intend to merge the other commits as well? (Github can be confusing at times).

**Comment by dspinellis** [comment]
I didn't see it in your last commit, and thought you didn't add it.  But now I see it in the code.  I need to document the flag though,

**Comment by nomeata** [comment]
The same for the other issues; I think all should be closed now.

**Comment by dspinellis** [comment]
A, excellent!  I'll try to find what do do with the documentation by diffing usage().

**Comment by dspinellis** [comment]
I think you're not measuring the size of a directory, right? Can you please add that code? I think a recursive stat (as you do for remove) is all that is needed.

**Comment by nomeata** [comment]
Oh, right, I forgot about this loose end. Sorry.

I don’t think there is a reliable way of measuring the size of a directory, due to hardlinks (very common with rsync-based backups) and stuff. Instead, `fileprune` should simply not allow the `-s` option if any argument is a directory.

**Comment by dspinellis** [comment]
Fair enough, given that you added `-S`.
