### ISSUE TITLE
Never deleted youngest file

### ISSUE THREAD

**Issue by nomeata** [dspinellis/fileprune#5]
Hi,

in certain circumstances, fileprune seems to be happy to delete the youngest backup. This is most likely not what you want, e.g. if there is a symbolic link pointing to the "latest" which is used as a source for `rsync --link-dest`. Maybe that should be special-cased?

(I’m still using my own fork which can handle directories and stuff, so if this does not apply to the mainline, sorry.)

Greetings,
Joachim

**Comment by dspinellis** [comment]
An option specifying files to retain?

**Comment by nomeata** [comment]
That might work, although it would be nice if the logic of figuring out “the latest” is inside fileprune, and not in some fragile shell script that calls it.

I’d be fine using an option, but I do wonder if deleting the youngest is a valid use-case at all.

**Comment by dspinellis** [comment]
Special casing the youngest file is problematic.  Why special-case one file, if you have multiple backups and their symlinks in the directory?  Also, if there's not enough space you might indeed want _fileprune_ to delete the youngest file.

**Comment by nomeata** [comment]
I would assume that most people run `create new backup; fileprune`. If `fileprune` can delete the youngest file, then the whole backup run was pointless.

Also, pracitically speaking, I expect my users to most likely want a just-deleted file back, so the youngest backup has the highest possibility of containing that.

> Also, if there's not enough space you might indeed want fileprune to delete the youngest file.

That’s a fair point, in some contexts.

So what if you allow the youngest file to be deleted, but only when there are no other backups? Those users who do _not_ care about the latest backup existing or not will probably not care about this occasional extra backup, and if space requirements demand it, it still gets deleted. But those users who _do_ care will be happy.

**Comment by dspinellis** [comment]
I actually run: `fileprune; backup` to ensure that space is there.  But this is irrelevant to our discussion.

I really don't think that the youngest file a an appropriate special case. _Fileprune_ is already tuned to prefer deleting older files than younger ones. If it deletes a young file, this could be a sign of a deeper problem, as was the case with #6.

**Comment by nomeata** [comment]
>  Fileprune is already tuned to prefer deleting older files than younger ones.

Not within one sequence! This is documented:

> By default \fIfileprune\fP will keep the oldest file within each day interval
> allowing files to migrate from one interval to the next as time goes by.

**Comment by dspinellis** [comment]
Thank you; very perceptive comment.  Given this, I think that the preservation of the youngest file should be treated as a special case via a command-line switch. The rationale is the one you gave: people typically want to recover files from the most recent backup.
