### ISSUE TITLE
Too much pruning with irregular backups

### ISSUE THREAD

**Issue by nomeata** [dspinellis/fileprune#6]
The setting `fileprune -e 1.25` works well for my backups which I do daily. But a backup that is only done occasional, I find the results surprising:

```
        2015-03-23.20h58
        2015-05-01.09h41
        2015-08-09.16h04
        2015-09-28.22h51
        2015-11-29.19h16
        2016-01-02.18h59
        2016-02-10.23h26
        2016-02-28.11h58
        2016-03-17.11h51
        2016-04-07.19h16
        2016-05-14.20h59
        2016-05-24.13h25
2016-05-31.19h39
2016-06-06.12h37
2016-06-28.10h29
```

The first column lists backups retained, while the second backups deleted. Why does it delete all those backups?

**Comment by nomeata** [comment]
Ah, is this because I did not specify a `count`? The line

```
                depth = max(count, nfiles);
```

indicates that it will schedule only `nfiles` schedule slot in this case, which is not what is desired here: If I do not give a max count, it should simply keep one backup per schedule slot!

**Comment by dspinellis** [comment]
I think what you suggest will change the current behavior.  Add an option for the behavior you want?

**Comment by nomeata** [comment]
Depends. As a software author, I am always reluctant to add options (more complexity for the author and the users).

The question is: Is the current behaviour sensible? Are there any users that likely rely on it? 

Also, I would expect a fileprune call to be idempotent (do you agree that this is a sensible behavior). I doubt that this is the case with the current code.

**Comment by dspinellis** [comment]
I agree that _fileprune_ should be idempotent; that's a good point.

More importantly, now that I'm looking at the code again, I think that the current behavior is buggy. There's no logical reason to setup the schedule's depth to nfiles (or count for that matter).  The depth should be long enough to cover the oldest file, right?

**Comment by nomeata** [comment]
Right!

**Comment by nomeata** [comment]
Just wondering if it makes sense for me to wait for a patch, or whether I am better off trying to come up with one myself :-)

**Comment by dspinellis** [comment]
I would very much appreciate a patch from you. (I know you work on a fork.)

**Comment by nomeata** [comment]
Ok, I have one. Please review.
